services:
  backend:
    build:
      context: ./src/dotnet
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  frontend:
    build:
      context: ./src/angular
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:4200:80"
    depends_on:
      - backend
