services:
  webgame:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - AllowedOrigins__0=https://letties.pl
